/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.matrixdashboard;

import java.sql.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author user1
 */
public class ActivityPanel extends javax.swing.JPanel {

    Activity a = null;

    /**
     * Creates new form ActivityPanel
     */
    public ActivityPanel(Activity a, Role r, Client c) {
        
        initComponents();
        
        Font font1 = new Font("Serif", Font.BOLD,12);
        Font font2 = new Font("Monospaced", Font.PLAIN,10);
        
        jActivityNameLabel.setText(a.name.trim());
        jClientLabel.setFont(font1);
 
        String abbrev = r.abbrev;
        if (abbrev.equals(Database.NONEABBREV))
            abbrev = "";
        jClientLabel.setText(abbrev.trim());
        jClientLabel.setFont(font2);
        
        String cname = c.name;
        if (cname.equals(Database.NONENAME))
            cname = "";
        jRoleLabel.setText(cname.trim());
        jRoleLabel.setFont(font2);
        
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(100, 60));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jActivityNameLabel = new javax.swing.JLabel();
        jRoleLabel = new javax.swing.JLabel();
        jClientLabel = new javax.swing.JLabel();

        jActivityNameLabel.setText("ActivityName");

        jRoleLabel.setText("Role");

        jClientLabel.setText("Client");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jActivityNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRoleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClientLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jActivityNameLabel)
                .addComponent(jRoleLabel)
                .addComponent(jClientLabel))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jActivityNameLabel;
    private javax.swing.JLabel jClientLabel;
    private javax.swing.JLabel jRoleLabel;
    // End of variables declaration//GEN-END:variables
}
